### ISSUE TITLE
Where is the CI?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/stsci.image#19]
There is a "test" folder but I don't see any CI set up. 😱

**Comment by jdavies-st** [comment]
Yeah, someone needs to add a `.travis.yml` file.  In the meantime, to run the tests in your checked out repo:
```
pip install -e .
pytest
```

**Comment by nden** [comment]
There was a decision to not do this until we consolidate the packages. Basically to avoid the effort of setting up testing for multiple packages when they may well become one package soon. We should be able to run them locally though.
